name: Create ceremony
on: 
  create
jobs:
  compile-and-prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run toolkit
      run: make create-locally unattended=true
    - name: Commit ceremony artifacts
      uses: stefanzweifel/git-auto-commit-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: Create '${{ github.ref }}' ceremony
        commit_options: '--no-verify'
        commit_user_name: Voceremony Bot
    - name: Create PR to end ceremony
      uses: peter-evans/create-pull-request@v5
      with:
        title: "On going ceremony: ${{ github.ref }}"
        token: ${{ github.token }}
        labels: "on-going-ceremony"
        assignees: ${{ github.actor }}
        body: "Close this PR without merge it to ends this ceremony"