name: Create ceremony
on: 
  create
jobs:
  compile-and-prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run toolkit
      run: make create unattended=true
    - uses: stefanzweifel/git-auto-commit-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: Create '${{ github.ref }}' ceremony
        commit_options: '--no-verify'
        commit_user_name: Voceremony Bot
    - uses: dacbd/create-issue-action@main
      name: Create issue to end ceremony
      with:
        title: "Ceremony: ${{ github.ref }}"
        token: ${{ github.token }}
        assignees: ${{ github.actor }}
        body: "Close this issue to ends this ceremony"