name: Create ceremony
on: 
  create
jobs:
  compile-and-prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run CLI
      run: make create unattended=true
    - uses: stefanzweifel/git-auto-commit-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: Create '${{ github.ref }}' ceremony
        commit_options: '--no-verify'
        commit_user_name: Voceremony Bot