name: Verify contribution
on: 
  pull_request:
    branches:
      - ceremony/*

permissions: write-all

jobs:
  verify-contribution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        lfs: true
        ref: ${{ github.ref }}
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run toolkit
      run: |
        docker build -q -t vocdoni/zk-voceremony --target zk-voceremony .
        docker run --rm -qt -v ./:/app --env-file ./ceremony.env vocdoni/zk-voceremony verify
    - name: Merge PR branch
      if: success() && contains(github.event.pull_request.title, 'Contribution:')
      run: |
        gh pr merge --admin --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}